KinderGartenSeckill.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace KinderGartenSeckill.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

KinderGartenSeckill.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace KinderGartenSeckill.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

KinderGartenSeckill.Web/Controllers/AdminController.cs
using KinderGartenSeckill.Model;
using KinderGartenSeckill.Service;
using KinderGartenSeckill.Web.Filter;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using KinderGartenSeckill.Dto;

namespace KinderGartenSeckill.Web.Controllers
{
    [AuthFilter(UserType.Actor, AllowUserType = UserType.Admin)]
    public class AdminController : KinderGartenSeckillControllerBase
    {
        private readonly IUserService _userService;
        private readonly IChildService _childService;
        private readonly IParentsService _parentService;
        public AdminController(IUserService userService,
            IChildService childService,
            IParentsService parentService) : base(userService)
        {
            this._userService = userService;
            this._childService = childService;
            this._parentService = parentService;
        }


        // GET: Admin
        public ActionResult Main()
        {
            var model = _userService.GetList();
            var actors = _userService.GetActors();
            ViewBag.Actors = actors;
            return View(model);
        }

        public ActionResult List(string username = null,
            string mobile = null,
            string taobaono = null,
            string garden = null,
            string ftime = null,
            string ttime = null,
            int actorUserId = 0)
        {
            var model = new List<UserListDto>();
            if (CurrUserType == UserType.Actor)
                model = _userService.GetUsers(userId: int.Parse(CurrUserId), username: username, mobile: mobile,
                    taobaono: taobaono, garden: garden,
                    ftime: ftime, ttime: ttime);
            else
                model = _userService.GetUsers(userId: actorUserId, username: username, mobile: mobile,
                    taobaono: taobaono, garden: garden,
                    ftime: ftime, ttime: ttime);
            //if (string.IsNullOrWhiteSpace(username) &&
            //    string.IsNullOrWhiteSpace(mobile) &&
            //    string.IsNullOrWhiteSpace(taobaono) &&
            //    string.IsNullOrWhiteSpace(garden) &&
            //    string.IsNullOrWhiteSpace(ftime) &&
            //    string.IsNullOrWhiteSpace(ttime))
            //{
            //    model = _userService.GetList();
            //}
            //else
            //{
            //    model = _userService.GetUsers(username, mobile, taobaono, garden, ftime, ttime);
            //}

            return PartialView(model);
        }

        public ActionResult SignTime()
        {
            return View();
        }

        public ActionResult Detail(int userId)
        {
            ViewBag.UserId = userId;
            return View();
        }

        public ActionResult _Child(int userId)
        {
            var model = _childService.GetChild(userId);
            return PartialView(model);
        }

        public ActionResult _Parents(int userId)
        {
            var model = _parentService.GetParents(userId);
            return PartialView(model);
        }

        public ActionResult ModifyUser(int userId)
        {
            var model = _userService.GetUser(userId);

            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "未报上", Value = "false" });
            items.Add(new SelectListItem { Text = "已报上", Value = "true" });
            ViewBag.StatusType = items;

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult ModifyUser(bm_user user)
        {
            var u = _userService.GetUser(user.Id);
            u.UserName = user.UserName;
            u.Mobile = user.Mobile;
            u.Email = user.Email;
            u.FirstKindergarten = user.FirstKindergarten;
            u.FirstUrl = user.FirstUrl;
            u.SecondKindergarten = user.SecondKindergarten;
            u.SecondUrl = user.SecondUrl;
            u.Operator = user.Operator;
            u.Status = user.Status;
            u.VerificationCode = user.VerificationCode;

            var model = _userService.Update(u);

            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "未报上", Value = "false" });
            items.Add(new SelectListItem { Text = "已报上", Value = "true" });
            ViewBag.StatusType = items;

            //return RedirectToAction("ModifyUser",);
            return View();
        }

        public ActionResult CustomPhrase(int userId)
        {
            bm_child childModel = _childService.GetChild(userId);
            bm_child_parents parentModel = _parentService.GetParents(userId);
            var arr = new ArrayList();
            var result1 = GetClassObj1(childModel);
            var result2 = GetClassObj1(parentModel);
            arr.AddRange(result1);
            arr.AddRange(result2);
            //return PartialView(result);
            return Json(arr, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        public ActionResult Export(int id)
        {
            var userId = id;
            List<string> disNames = new List<string>();

            bm_child childModel = _childService.GetChild(userId);
            bm_child_parents parentModel = _parentService.GetParents(userId);
            bm_user userModel = _userService.GetUser(userId);

            var result = GetClassObj(childModel);
            var folder = $"{userModel?.FirstRegistrationTime.Value.ToString("yyyyMMdd-hhmm")}";
            var file = $"{userModel?.Mobile}-{childModel?.ChildName}.txt";
            string fullpath = Server.MapPath("../../Export/" + folder + "/" + file);

            Encoding code = Encoding.GetEncoding("gb2312");
            StreamWriter sw = null;
            {
                try
                {
                    DirectoryInfo dir = new DirectoryInfo(Server.MapPath(folder));
                    if (!dir.Exists)
                    {
                        dir.Create();
                    }

                    sw = new StreamWriter(fullpath, false, code);
                    sw.Write(result);
                    sw.Flush();

                }
                catch { }
            }
            sw.Close();
            sw.Dispose();
            var url = $"{ ConfigurationManager.AppSettings["website"]}{"Export/" + folder + "/" + file}";
            return Redirect(url);
            //return Json(url,JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 用户分配
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ChildAssignment()
        {
            var operators = await _userService.GetOperators();
            ViewBag.Operators = operators;

            //查询未分配的用户
            var validList = _userService.GetValidUsers();
            return View(validList);
        }

        /// <summary>
        /// 获取已分配的用户
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetSelectedUsers(int id)
        {
            var users = _userService.GetSelected(id);
            return Json(users, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Assignment(int id, List<int> users)
        {
            var result = await _userService.Assignment(id, users);
            return Json(new
            {
                IsSussess = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Js()
        {
            return View();
        }
    }
}

KinderGartenSeckill.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using KinderGartenSeckill.Web.Models.Layout;
using KinderGartenSeckill.Service;

namespace KinderGartenSeckill.Web.Controllers
{
    public class LayoutController : KinderGartenSeckillControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILanguageManager _languageManager;
        private readonly IUserService _userService;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ILanguageManager languageManager,
            IUserService userService) : base(userService)
        {
            _userNavigationManager = userNavigationManager;
            _languageManager = languageManager;
            _userService = userService;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

KinderGartenSeckill.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="宝贝联盟e点通">
    <meta name="keywords" content="天津幼儿园报名 天津幼儿园秒杀 南开,河西,河东,红桥,河北">
    <meta name="description" content="天津幼儿园报名 天津幼儿园秒杀 南开,河西,河东,红桥,河北">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>天津幼儿园报名秒杀-宝贝联盟e点通</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")
    @Styles.Render("~/Bundles/My")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")
    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")
	
</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>



    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';        
        //moment.locale('@Thread.CurrentThread.CurrentUICulture.Name'); //Localizing momentjs
        
        @*moment.defineLocaleCN('@Thread.CurrentThread.CurrentUICulture.Name'); //Localizing momentjs*@
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

KinderGartenSeckill.Web/Views/Shared/_TopBar.cshtml
@using KinderGartenSeckill.Web.Controllers
@{
    var baseContext = ((KinderGartenSeckillControllerBase)this.ViewContext.Controller);
}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> 宝贝联盟e点通</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <a class="navbar-brand" href="@Url.Action("Result", "Home")"><i class="fa fa-user"></i> 成功案例</a>
                <a class="navbar-brand" href="@Url.Action("SignTime", "Home")"><i class="fa fa-clock-o"></i> 报名时间</a>
                @if (!baseContext.IsLogin)
                {
                    <a class="navbar-brand" href="@Url.Action("Login", "User")"><i class="fa fa-sign-in"></i> 登录</a>


                    @*@Html.Action("LanguageSelection", "Layout")*@
                }
                else
                {
                    if (baseContext.CurrUserType == KinderGartenSeckill.Model.UserType.Admin)
                    {
                        <a class="navbar-brand" href="@Url.Action("Regist", "User")"><i class="fa fa-registered"></i> 注册</a>
                        <a class="navbar-brand" href="@Url.Action("Main", "Admin")"><i class="fa fa-list"></i> 报名列表</a>
                        <a class="navbar-brand" href="@Url.Action("Js", "Admin")"><i class="fa fa-download"></i> 脚本下载</a>
                        @*<a class="navbar-brand" href="@Url.Action("SignTime", "Admin")"><i class="fa fa-user"></i> 报名时间</a>*@
                    }
                    else if (baseContext.CurrUserType == KinderGartenSeckill.Model.UserType.Actor)
                    {
                        <a class="navbar-brand" href="@Url.Action("Main", "Admin")"><i class="fa fa-list"></i> 报名列表</a>
                        <a class="navbar-brand" href="@Url.Action("Js", "Admin")"><i class="fa fa-download"></i> 脚本下载</a>
                        @*<a class="navbar-brand" href="@Url.Action("SignTime", "Admin")"><i class="fa fa-user"></i> 报名时间</a>*@
                    }
                    else
                    {
                        <a class="navbar-brand" href="@Url.Action("Info", "Customer")"><i class="fa fa-user"></i> 个人信息</a>
                        @*<a class="navbar-brand" href="@Url.Action("RegistComplete", "User")"><i class="fa fa-user"></i> 个人信息</a>*@
                        @*<a class="navbar-brand" href="@Url.Action("Child","Customer")"><i class="fa fa-user"></i> 个人信息</a>*@
                    }
                    <a class="navbar-brand" href="@Url.Action("Logout", "User")"><i class="fa fa-sign-out"></i> 注销</a>
                }
            </ul>
        </div>
    </div>
</div>